name: 'Deploy action for GitHub Pages'
description: 'GitHub Actions for GitHub Pages 🚀 Deploy static files and publish your site easily. Static-Site-Generators-friendly.'
author: 'peaceiris'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  emptyCommits:
    description: 'If empty commits should be made to the publication branch'
    required: false
    default: 'true'
  keepFiles:
    description: 'If existing files in the publish branch should be not removed before deploying'
    required: false
    default: 'false'
