name: docker image ci

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
    - 'README.md'
    - 'website'
    - '.github/workflows/gh-pages.yml'
  push:
    paths-ignore:
    - 'README.md'
    - 'website'
    - '.github/workflows/gh-pages.yml'
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1

    - name: build
      env:
        DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/action:latest
      run: |
        docker build . --file Dockerfile --tag ${DOCKER_IMAGE} ||
        (echo -e "\e[31m[${GITHUB_WORKFLOW}] failed to build\e[m" && exit 1)

  shellcheck:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: shellcheck
      run: shellcheck ./entrypoint.sh

  hadolint:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: hadolint
      run: |
        brew install hadolint
        hadolint ./Dockerfile
